apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-new-cron-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-cron-job
            image: node:14-alpine
            imagePullPolicy: Always
            args:
            - -e
            - "console.log(new Date().toString());"
          restartPolicy: OnFailure
