{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{ else }}
apiVersion: policy/v1beta1
{{ end -}}
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-world.fullname" . }}-pdb
  labels:
  {{- include "hello-world.labels" . | nindent 4 }}
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: hello-world