apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}-hello-world
  labels:
    app: hello-world
  {{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helloWorld.type }}
  selector:
    app: hello-world
  {{- include "hello-world.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.helloWorld.ports | toYaml | nindent 2 -}}